### ISSUE TITLE
Scikit-learn problems and Topographic product with SOMPY?

### ISSUE THREAD

**Issue by olafjarroyo** [FlorentF9/SOMperf#2]
Hello, 
I have one problem and one question:

1)While loading the SOMperf libraries, I receive an error from the external methods: **No module named 'sklearn.metrics.cluster.supervised'**. Research online suggest this might occur because of a mix of pip and conda-versions of libraries, but I tried in another computer with only conda-installed libraries, and sadly the same problem occurs.

2) Is there a way to estimate the topographic product with SOMperf using SOMPY?

Thank you very much!

Olaf

**Comment by FlorentF9** [comment]
Hi, 

1. it seems that the module name has changed, a fix has been suggested [in this issue](https://github.com/FlorentF9/SOMperf/issues/4#issuecomment-1470362469). When I have some time I will update the code for the latest versions.

2. Have you already tried using `somperf.metrics.topographic_product` ? You just need to provide the code vectors obtained with SOMpy, and the distance function on the map (probably, `sompy.utils.rectangular_topology_dist`).
