### ISSUE TITLE
Missing sklearn modules

### ISSUE THREAD

**Issue by rravenel** [FlorentF9/SOMperf#4]
MacOS Monterey 12.2.1
I'm using current stable sklearn (1.1.1), Python 3.8.9.  I hit the following errors:

File "/Users/rene/.venv/ahead2/lib/python3.8/site-packages/SOMperf-0.2b0-py3.8.egg/somperf/metrics/external.py", line 6, in <module>
ModuleNotFoundError: No module named 'sklearn.metrics.cluster.supervised'

somperf/metrics/external.py, line 6: from `sklearn.metrics.cluster.supervised import check_clusterings`

I managed to find sklearn source here (0.17.1): `https://gemfury.com/stream/python:scikit-learn/-/content/metrics/cluster/supervised.py`; pasted the `check_clusterings` definition into `external.py`, reinstalled and then hit the following:

File "/Users/rene/.venv/ahead2/lib/python3.8/site-packages/SOMperf-0.2b0-py3.8.egg/somperf/metrics/external.py", line 7, in <module>
ModuleNotFoundError: No module named 'sklearn.utils.linear_assignment_'

sklearn 0.17.1 won't build on my machine. 0.22.2 doesn't have these problems, but consistently segfaults.

Please add version numbers to `requirements.txt` (and maybe reply here with them, too).

Thank you.

**Comment by hbanderier** [comment]
Hi, just stumbled upon this and maybe it can help people in the future / be fixed in the main branch
I fixed these issues by replacing the sklearn imports in `external.py` by
```python
from sklearn.metrics.cluster._supervised import check_clusterings
from scipy.optimize import linear_sum_assignment as linear_assignment
```
Hope it helps !
